# Generated by Django 5.1.5 on 2025-02-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_service_mappings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemapping',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='servicemappingtype',
            name='schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
