# Generated by Django 5.1.5 on 2025-02-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_service_mappings', '0002_alter_servicemapping_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemapping',
            old_name='type',
            new_name='mapping_type',
        ),
        migrations.CreateModel(
            name='MappingTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('mapping_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netbox_service_mappings.servicemappingtype')),
            ],
        ),
        migrations.CreateModel(
            name='MappingRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netbox_service_mappings.servicemapping')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netbox_service_mappings.mappingtypefield')),
            ],
        ),
    ]
