# Generated by Django 5.1.5 on 2025-02-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_service_mappings', '0003_rename_type_servicemapping_mapping_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtypefield',
            name='field_type',
            field=models.CharField(default='object', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappingtypefield',
            name='many',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mappingrelation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='netbox_service_mappings.mappingtypefield'),
        ),
        migrations.AlterField(
            model_name='mappingtypefield',
            name='mapping_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='netbox_service_mappings.servicemappingtype'),
        ),
    ]
