# Generated by Django 5.1.5 on 2025-02-18 18:53

import random
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_service_mappings', '0004_mappingtypefield_field_type_mappingtypefield_many_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtypefield',
            name='name',
            field=models.CharField(default='', max_length=100, ),
            preserve_default=False,
        ),
    ]
