# Generated by Django 5.1.5 on 2025-02-18 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_service_mappings', '0005_mappingtypefield_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtypefield',
            name='label',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mappingtypefield',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
