# Generated by Django 5.1.5 on 2025-02-18 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_service_mappings', '0006_mappingtypefield_label_alter_mappingtypefield_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingrelation',
            name='content_type',
        ),
        migrations.AddField(
            model_name='mappingtypefield',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
