# Generated by Django 5.1.5 on 2025-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_service_mappings', '0007_remove_mappingrelation_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingrelation',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
