# Generated by Django 5.1.6 on 2025-02-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_service_mappings', '0008_alter_mappingrelation_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemappingtype',
            name='version',
        ),
    ]
