# Generated by Django 5.1.6 on 2025-03-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_service_mappings', '0009_remove_servicemappingtype_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtypefield',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
