# Generated by Django 5.1.6 on 2025-03-03 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_service_mappings', '0010_mappingtypefield_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingtypefield',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
