# Generated by Django 5.2b1 on 2025-04-18 12:15

import re

import django.core.validators
import django.db.models.deletion
import taggit.managers
import utilities.json
import utilities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0012_job_object_type_optional"),
        ("extras", "0123_journalentry_kind_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomObjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("schema", models.JSONField(blank=True, default=dict)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Object Type",
            },
        ),
        migrations.CreateModel(
            name="CustomObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "custom_object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_objects",
                        to="netbox_custom_objects.customobjecttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Object",
            },
        ),
        migrations.CreateModel(
            name="CustomObjectTypeField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("type", models.CharField(default="text", max_length=50)),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                flags=re.RegexFlag["IGNORECASE"],
                                message="Only alphanumeric characters and underscores are allowed.",
                                regex="^[a-z0-9_]+$",
                            ),
                            django.core.validators.RegexValidator(
                                flags=re.RegexFlag["IGNORECASE"],
                                inverse_match=True,
                                message="Double underscores are not permitted in custom field names.",
                                regex="__",
                            ),
                        ],
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("group_name", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("required", models.BooleanField(default=False)),
                ("unique", models.BooleanField(default=False)),
                ("search_weight", models.PositiveSmallIntegerField(default=1000)),
                ("filter_logic", models.CharField(default="loose", max_length=50)),
                ("default", models.JSONField(blank=True, null=True)),
                ("related_object_filter", models.JSONField(blank=True, null=True)),
                ("weight", models.PositiveSmallIntegerField(default=100)),
                ("validation_minimum", models.BigIntegerField(blank=True, null=True)),
                ("validation_maximum", models.BigIntegerField(blank=True, null=True)),
                (
                    "validation_regex",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        validators=[utilities.validators.validate_regex],
                    ),
                ),
                ("ui_visible", models.CharField(default="always", max_length=50)),
                ("ui_editable", models.CharField(default="yes", max_length=50)),
                ("is_cloneable", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True)),
                (
                    "choice_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="choices_for_object_type",
                        to="extras.customfieldchoiceset",
                    ),
                ),
                (
                    "custom_object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="netbox_custom_objects.customobjecttype",
                    ),
                ),
                (
                    "related_object_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.objecttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "custom object type field",
                "verbose_name_plural": "custom object type fields",
                "ordering": ["group_name", "weight", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomObjectRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                (
                    "custom_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="netbox_custom_objects.customobject",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="netbox_custom_objects.customobjecttypefield",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="customobjecttypefield",
            constraint=models.UniqueConstraint(
                fields=("name", "custom_object_type"),
                name="netbox_custom_objects_customobjecttypefield_unique_name",
            ),
        ),
    ]
