# Generated by Django 5.2.7 on 2025-10-20 13:24

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_configrevision_active'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_custom_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customobjecttype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='netbox_custom_objects_customobjecttype_slug', violation_error_message='A Custom Object Type with this slug already exists.'),
        ),
    ]
