# Generated by Django 5.2.2 on 2025-07-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_custom_objects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customobject",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="customobject",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
