# Generated by Django 5.2b1 on 2025-03-26 23:41

import django.core.validators
import django.db.models.deletion
import re
import utilities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_job_object_type_optional'),
        ('extras', '0123_journalentry_kind_default'),
        ('netbox_custom_objects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customobjecttypefield',
            old_name='many',
            new_name='is_cloneable',
        ),
        migrations.RemoveField(
            model_name='customobjecttypefield',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customobjecttypefield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='customobjecttypefield',
            name='options',
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='choice_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='choices_for_object_type', to='extras.customfieldchoiceset'),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='default',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='filter_logic',
            field=models.CharField(default='loose', max_length=50),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='group_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='object_types',
            field=models.ManyToManyField(related_name='custom_object_types', to='core.objecttype'),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='related_object_filter',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='related_object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.objecttype'),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='search_weight',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='type',
            field=models.CharField(default='text', max_length=50),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='ui_editable',
            field=models.CharField(default='yes', max_length=50),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='ui_visible',
            field=models.CharField(default='always', max_length=50),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='validation_maximum',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='validation_minimum',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='validation_regex',
            field=models.CharField(blank=True, max_length=500, validators=[utilities.validators.validate_regex]),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='customobjecttypefield',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customobjecttypefield',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Only alphanumeric characters and underscores are allowed.', regex='^[a-z0-9_]+$'), django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='Double underscores are not permitted in custom field names.', regex='__')]),
        ),
    ]
