# Generated by Django 5.2b1 on 2025-04-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_custom_objects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customobjecttype",
            options={"ordering": ("name",)},
        ),
    ]
