# Generated by Django 5.2.5 on 2025-08-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_custom_objects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customobjecttype",
            name="slug",
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customobjecttype",
            name="verbose_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
