# Generated by Django 5.2.2 on 2025-07-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_custom_objects",
            "0002_customobject_created_customobject_last_updated",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomObject",
        ),
    ]
