# Generated by Django 5.2.8 on 2025-12-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_custom_objects", "0002_ensure_fk_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="customobjecttype",
            name="cache_timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
