# Generated by Django 5.2b1 on 2025-03-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_custom_objects', '0002_rename_many_customobjecttypefield_is_cloneable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customobjecttypefield',
            name='custom_field_data',
        ),
        migrations.RemoveField(
            model_name='customobjecttypefield',
            name='object_types',
        ),
        migrations.RemoveField(
            model_name='customobjecttypefield',
            name='tags',
        ),
    ]
