# Generated by Django 5.2b1 on 2025-05-21 23:43

import django.db.models.deletion
import netbox_custom_objects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_custom_objects', '0002_alter_customobjecttype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomObjectObjectType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contenttypes.contenttype',),
            managers=[
                ('objects', netbox_custom_objects.models.CustomObjectObjectTypeManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customobjecttype',
            name='slug',
        ),
        migrations.AddField(
            model_name='customobjecttype',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
