# Generated by Django 5.2.2 on 2025-07-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_custom_objects", "0003_delete_customobject"),
    ]

    operations = [
        migrations.AddField(
            model_name="customobjecttype",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
