# Generated by Django 5.2b1 on 2025-03-27 14:21

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_job_object_type_optional'),
        ('extras', '0123_journalentry_kind_default'),
        ('netbox_custom_objects', '0003_remove_customobjecttypefield_custom_field_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customobjecttypefield',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Only alphanumeric characters and underscores are allowed.', regex='^[a-z0-9_]+$'), django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], inverse_match=True, message='Double underscores are not permitted in custom field names.', regex='__')]),
        ),
        migrations.AddConstraint(
            model_name='customobjecttypefield',
            constraint=models.UniqueConstraint(fields=('name', 'custom_object_type'), name='netbox_custom_objects_customobjecttypefield_unique_name'),
        ),
    ]
