# Generated by Django 5.2.11 on 2026-02-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_custom_objects', '0003_ensure_fk_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='customobjecttype',
            name='group_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
