# Generated by Django 5.2.5 on 2025-09-04 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_concrete_objecttype"),
        ("netbox_custom_objects", "0003_customobjecttype_object_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customobjecttype",
            name="object_type",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_object_types",
                to="core.objecttype",
            ),
        ),
    ]
