# Generated by Django 5.2.2 on 2025-07-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_custom_objects", "0004_customobjecttype_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customobjecttype",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
