# Generated by Django 5.2b1 on 2025-03-30 22:53

import extras.models.customfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_custom_objects', '0004_alter_customobjecttypefield_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customobjecttypefield',
            managers=[
                ('objects', extras.models.customfields.CustomFieldManager()),
            ],
        ),
    ]
