# Generated by Django 5.2.1 on 2025-06-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_custom_objects', '0004_customobjecttypefield_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customobjecttype',
            name='verbose_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customobjecttype',
            name='verbose_name_plural',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
