# Generated by Django 5.2.12 on 2026-04-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_custom_objects', '0004_customobjecttype_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customobjecttypefield',
            name='context',
            field=models.BooleanField(default=False),
        ),
    ]
