# Generated by Django 5.2.12 on 2026-04-05 00:53

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_job_queue_name'),
        ('extras', '0134_owner'),
        ('netbox_custom_objects', '0004_customobjecttype_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customobjecttypefield',
            name='related_name',
            field=models.CharField(
                blank=True,
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        flags=re.RegexFlag['IGNORECASE'],
                        message='Only alphanumeric characters and underscores are allowed.', regex='^[a-z0-9_]+$',
                    )
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name='customobjecttypefield',
            constraint=models.UniqueConstraint(
                condition=models.Q(('related_name__gt', '')),
                fields=('related_object_type', 'related_name'),
                name='netbox_custom_objects_customobjecttypefield_unique_related_name',
            ),
        ),
    ]
