# Generated by Django 5.2b1 on 2025-04-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_custom_objects', '0005_alter_customobjecttypefield_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customobjecttypefield',
            options={'ordering': ['group_name', 'weight', 'name']},
        ),
        migrations.AlterModelManagers(
            name='customobjecttypefield',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customobject',
            name='custom_field_data',
        ),
    ]
