# Generated by Django 5.2.4 on 2025-08-12 17:38

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_custom_objects", "0005_alter_customobjecttype_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customobjecttypefield",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        flags=re.RegexFlag["IGNORECASE"],
                        message="Only alphanumeric characters and underscores are allowed.",
                        regex="^[a-z0-9_]+$",
                    ),
                    django.core.validators.RegexValidator(
                        flags=re.RegexFlag["IGNORECASE"],
                        inverse_match=True,
                        message="Double underscores are not permitted in custom object field names.",
                        regex="__",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customobjecttypefield",
            name="search_weight",
            field=models.PositiveSmallIntegerField(default=500),
        ),
    ]
