# Generated by Django 5.2.1 on 2025-06-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_custom_objects', '0005_customobjecttype_verbose_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customobjecttype',
            name='verbose_name',
        ),
    ]
