# Generated by Django 5.2.12 on 2026-04-08 01:04

import netbox_custom_objects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_custom_objects', '0006_backfill_schema_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customobjecttype',
            name='version',
            field=models.CharField(blank=True, max_length=50, validators=[netbox_custom_objects.models._validate_semver]),
        ),
        migrations.AlterField(
            model_name='customobjecttypefield',
            name='deprecated_since',
            field=models.CharField(blank=True, max_length=50, validators=[netbox_custom_objects.models._validate_semver]),
        ),
        migrations.AlterField(
            model_name='customobjecttypefield',
            name='scheduled_removal',
            field=models.CharField(blank=True, max_length=50, validators=[netbox_custom_objects.models._validate_semver]),
        ),
        migrations.AlterField(
            model_name='customobjecttypefield',
            name='schema_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
