# Generated by Django 5.2.12 on 2026-04-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_job_queue_name'),
        ('extras', '0134_owner'),
        ('netbox_custom_objects', '0006_customobjecttypefield_related_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customobjecttype',
            name='next_schema_id',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='customobjecttype',
            name='schema_document',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='deprecated_since',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='scheduled_removal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customobjecttypefield',
            name='schema_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customobjecttype',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='customobjecttypefield',
            constraint=models.UniqueConstraint(
                condition=models.Q(('schema_id__isnull', False)),
                fields=('schema_id', 'custom_object_type'),
                name='netbox_custom_objects_customobjecttypefield_unique_schema_id',
            ),
        ),
    ]