# Generated by Django 5.2.1 on 2025-06-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_custom_objects', '0006_remove_customobjecttype_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customobjecttype',
            name='verbose_name_plural',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
