# Generated by Django 5.2.1 on 2025-06-05 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_custom_objects", "0007_alter_customobjecttype_verbose_name_plural"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customobjecttype",
            name="content_type",
        ),
    ]
