# Generated by Django 5.2.2 on 2025-06-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_custom_objects", "0008_remove_customobjecttype_content_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomObjectRelation",
        ),
    ]
