# Generated by Django 5.2.2 on 2025-06-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_custom_objects", "0009_delete_customobjectrelation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customobject",
            name="custom_object_type",
        ),
        migrations.RemoveField(
            model_name="customobject",
            name="data",
        ),
        migrations.RemoveField(
            model_name="customobject",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customobject",
            name="tags",
        ),
    ]
