# Generated by Django 5.2.2 on 2025-06-20 22:57

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0129_fix_script_paths"),
        (
            "netbox_custom_objects",
            "0010_remove_customobject_custom_object_type_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customobjecttype",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="netbox_custom_objects_customobjecttype_name",
                violation_error_message="A Custom Object Type with this name already exists.",
            ),
        ),
    ]
