# Generated by Django 6.0.5 on 2026-06-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_custom_objects', '0014_fix_mixed_case_field_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='customobjecttype',
            name='changelog_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
