# Generated by Django 6.0.6 on 2026-06-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_custom_objects", "0014_fix_mixed_case_field_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="customobjecttype",
            name="config_context_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
